# Generated by Django 2.0.3 on 2018-03-29 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateField(null=True)),
                ('page_link', models.URLField(null=True)),
                ('image_link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('MAIN', 'Main'), ('SUPPORT', 'Supporting')], max_length=200)),
                ('page_link', models.URLField(null=True)),
                ('image_link', models.URLField(null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('anime', models.ManyToManyField(to='seiyuu_mgr.Anime')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('starting_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Seiyuu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('page_link', models.URLField(null=True)),
                ('image_link', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='seiyuu',
            field=models.ManyToManyField(to='seiyuu_mgr.Seiyuu'),
        ),
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seiyuu_mgr.Season'),
        ),
    ]
